port: "80"

mongo:
  database: "coins"
  host: "mongo"
  port: "27017"

redis:
  host: "redis"
  port: "6379"
  password: ""
  db: 0

kafka:
  address:
    - "localhost:9091"
  topic:
    - "analytic"